config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'patients/registrations'
  }

  root to: 'users#show'
  resources :appointments, only: %i[create edit update]
  resources :doctors
  resources :patients
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  validates :phone_number, uniqueness: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    where(phone_number: conditions[:phone_number]).first
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  MAX_DOCTOR_APPOINTMENTS = 10

  enum status: { active: 1, inactive: 0 }
  belongs_to :patient
  belongs_to :doctor
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true
  has_many :doctors, dependent: :destroy
end

app/models/doctor.rb
class Doctor < User
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
  belongs_to :category, optional: true
end

app/models/patient.rb
class Patient < User
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :avatar, file_size: { less_than: 1.megabytes }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :phone_number, uniqueness: true

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    where(phone_number: conditions[:phone_number]).first
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # binding.pry

  def after_sign_in_path_for(user)
    case user
    when Doctor then doctor_path(current_user.id)
    when Patient then patient_path(current_user.id)
    when AdminUser then admin_root_path
    else
      root_path
    end
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:warning] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:phone_number])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :require_create, only: [:create]
  def edit
    authorize Appointment
    @appointment = Appointment.find_by(id: params[:id]).decorate
  end

  def create
    authorize Appointment
    @appointment = Appointment.create(doctor_id: params[:doctor_id],
                                      patient_id: current_user.id,
                                      status: :active)
    if @appointment.save
      redirect_to patient_path(current_user.id), flash: { notice: t('.successfully_appointment') }
    else
      redirect_to patient_path, flash: { alert: t('.error_appointment') }
    end
  end

  def update
    authorize Appointment
    @appointment = Appointment.find_by(id: params[:id])

    if @appointment.update(appointment_params)
      redirect_to doctor_path, flash: { notice: t('.successfully_recommendation') }
    else
      render 'edit', flash: { alert: t('.error_recommendation') }
    end
  end

  private

  def appointment_params
    params.require(:appointment)
          .permit(:recommendation)
          .merge(status: :inactive)
  end

  def require_create
    doctor = Doctor.find_by(id: params[:doctor_id])
    if doctor.appointments.active.count >= Appointment::MAX_DOCTOR_APPOINTMENTS
      redirect_to patient_path(id: current_user.id), flash: { alert: t('.has_max_appointments', max_doctor_appointments:
      Appointment::MAX_DOCTOR_APPOINTMENTS) }
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    authorize Doctor
    @active_patients = current_user.appointments.includes([:patient]).active.decorate
  end

  def update
    @doctor = Doctor.find_by(id: params[:id])

    if @doctor.update(doctor_params)
      redirect_to doctor_path, flash: { notice: 'Avatar save' }
    else
      redirect_to doctor_path, flash: { alert: 'Avatar dont save' }
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(:avatar)
  end
end

app/controllers/patients/registrations_controller.rb
class Patients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  def create
    params[:user] = params[:user]&.merge(type: Patient.name)
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[type])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
    authorize Patient
    @categories = Category.includes([:doctors]).all.decorate
    @inactive_appointment = current_user.appointments.includes([:doctor]).inactive
  end

  def update
    @patient = Patient.find_by(id: params[:id])
    # binding.pry
    if @patient.update(patient_params)
      redirect_to patient_path, flash: { notice: 'Avatar save' }
    else
      redirect_to patient_path, flash: { alert: 'Avatar dont save' }
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.haml
.text-center
  = current_user.name
  = t('.title')
  = @appointment.patient_name
.content_center
  = simple_form_for @appointment do |f|
    = f.input :recommendation
    = f.button :submit, t('.save'),class: "btn-primary"

app/views/doctors/show.html.haml
.container
  %button.btn.btn-primary.mt-3.mb-3{"data-target" => "#exampleModal", "data-toggle" => "modal", type: "button"}
    = t('.upload_avatar')

#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title
          = t('.upload_photo')
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_for current_user do |f|
          = f.file_field :avatar
          = f.submit 'Load', class: "btn btn-primary modal-footer mt-2"

.container
  .row
    - @active_patients.each do |appointment|
      .col.mb-4
        .card.cart_width
          %img.card-img-top
          = image_tag(appointment.patient.avatar.url) if appointment.patient.avatar?
          .card-body.pb-2
            %h5.card-title
              = appointment.patient_name
          %ul.list-group.list-group-flush
            %li.list-group-item
              = appointment.patient.phone_number
            %li.btn.btn-success 
              = appointment.status
          .card-body.p0
            = link_to t('.save'), edit_appointment_path(appointment), class: 'btn btn-primary'

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 
      = t('.project_name')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-expand-lg.navbar-dark.bg-primary.justify-content-between.bg-danger
      .container
        %div
          %h4.mb-0
            .navbar-brand
              = link_to t('.project_name'), current_user, class: "nav-item text-white"
        %div
          .navbar-nav
            - if user_signed_in?
              %span.text-white
                = image_tag(current_user.avatar.url,:class => "img_preview") if current_user.avatar?
                = t('.hello') 
                #{current_user.phone_number}
                = link_to t('.exit'), destroy_user_session_path, method: :delete, class: "text-white"
            - else
              = link_to t('.sign_in'), new_user_session_path, class: "nav-item nav-link text text-white"
              = link_to t('.sign_up'), new_user_registration_path, class: "nav-item nav-link text-white"
    - flash.each do |key, value|
      %div{class: "alert alert-#{key} alert-dismissible", role: "alert"}
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
          %span{"aria-hidden" => "true"} ×
        = value
    = yield
    

app/views/patients/show.html.haml
.container
  %button.btn.btn-primary.mt-3.mb-3{"data-target" => "#exampleModal", "data-toggle" => "modal", type: "button"}
    = t('.upload_avatar')
  %button.btn.btn-success.mt-3.mb-3{"data-target" => "#RecomendModal", "data-toggle" => "modal", type: "button"}
    = t('.my_recommendation')

  #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog{role: "document"}
      .modal-content
        .modal-header
          %h5#exampleModalLabel.modal-title
            = t('.upload_photo')
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          = form_for current_user do |f|
            = f.file_field :avatar
            = f.submit 'Load', class: "btn btn-primary modal-footer mt-2"
  #RecomendModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog{role: "document"}
      .modal-content
        .modal-header
          %h5#exampleModalLabel.modal-title
            = t('.list_recommendation')
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          - @inactive_appointment.each do |appointment|
            .border.mb-3.pl-3
              = appointment.doctor.name
              %br
              = appointment.recommendation
              %br
              %p.btn.btn-danger.mb-1
                = appointment.status
              %br
.container
  .row
    - @categories.each do |category|
      - category.doctors.each do |doctor|
        .col.mb-4
          .card.cart_width
            %img.card-img-top
            = image_tag(doctor.avatar.url) if doctor.avatar?
            .card-body.pb-2
              %h5.card-title
                = doctor.name
            %ul.list-group.list-group-flush
              %li.list-group-item
                = category.name
              %li.list-group-item
                = doctor.phone_number
            .card-body.pb-1
              = button_to t('.save'), appointments_path(doctor_id: doctor.id), class:"btn btn-success"

app/views/users/show.html.haml
.hit-the-floor :Codica